In [429]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [430]:
%autoreload 2

In [431]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from src.models.decision_tree import DecisionTree

In [432]:
datafile = "../data/processed/bc.csv"
df = pd.read_csv(datafile, index_col="Sample")
df['Class'] = pd.get_dummies(df['Class'])[4]
df.tail()

Clump Thickness  Cell Size Uniformity  ...    Mitoses  Class
Sample                                         ...                  
776715                3                     1  ...          1      0
841769                2                     1  ...          1      0
888820                5                    10  ...          2      1
897471                4                     8  ...          1      1
897471                4                     8  ...          1      1

[5 rows x 10 columns]

In [433]:
np.random.seed(42)

In [434]:
train, validate, test = np.split(df.sample(frac=1), [int(.6*len(df)), int(.8*len(df))])

In [435]:
x_cols = train.columns[:-1]
y_cols = train.columns[-1:]

In [436]:
impurity_options = ['entropy', 'gini', 'misclassification']
depth_options = [2, 3, 4, 5, 6, 7, 8, 9, 10]

In [437]:
options_1 = []
for io in impurity_options:
    for do in depth_options:
        options_1.append((io, do))

In [438]:
dt = DecisionTree().fit(train)

0.9401377669751032
0.5940812491539162
0.4579685237376072
0.38142328777475887
0.33113315876801286
0.33113315876801286
0.33113315876801286
0.33113315876801286
0.33113315876801286
0.33113315876801286
0.33113315876801286
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
-0.0
I Found a leaf
-0.0
I Found a leaf
-0.0
I Found a leaf
0.07885601377455281
0.07885601377455281
0.07885601377455281
0.07885601377455281
0.07885601377455281
0.07885601377455281
0.07885601377455281
0.07885601377455281
0.07885601377455281
0.07885601377455281
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf
0.0
I Found a leaf


In [439]:
v = validate.loc[validate.index[0]]
v["Mitoses"]

1

In [440]:
dt.s_predict(v)

array([0], dtype=uint8)

In [441]:
dt.s_predict(v)

array([0], dtype=uint8)

In [442]:
i = validate.index[0]

In [443]:
i

1239420

In [444]:
v

Clump Thickness                1
Cell Size Uniformity           1
Cell Shape Uniformity          1
Marginal Adhesion              1
Single Epithelial Cell Size    2
Bare Nuclei                    1
Bland Chromatin                1
Normal Nuclei                  1
Mitoses                        1
Class                          0
Name: 1239420, dtype: int64

In [445]:
print(dt.left_)

Node split on Clump Thickness at 8.5


In [446]:
print(dt.right_)

Node split on Clump Thickness at 10.5


In [447]:
print(dt)

Node split on Cell Size Uniformity at 4.5


In [448]:
dt.left_.right_

Leaf valued [1]

In [449]:
from scipy.stats import mode

In [450]:
mode([1, 1, 0])

ModeResult(mode=array([1]), count=array([2]))

In [451]:
mode([1, 1, 0, 0]).mode

array([0])